POST http://localhost:8000/login
Content-Type: application/x-www-form-urlencoded

email=chief@mail.com&password=password


GET http://localhost:8000/api/user/create
Authorization: Bearer votre_jeton_de_session

GET http://localhost:8000/api/specialties
Authorization: Bearer {1|p9oz3YfaZkEynUS2hO2MTh9eDtdKp67bXT3hZpadc865cd57}

GET http://localhost:8000/api/patients
Authorization: Bearer {7|BrTjSrwJrNdyXpZUeOdnuz1mHnxYPgGtmSfobyQI9e8df099}

GET http://localhost:8000/api/patient/{1}
Authorization: Bearer {1|p9oz3YfaZkEynUS2hO2MTh9eDtdKp67bXT3hZpadc865cd57}

GET http://localhost:8000/api/specialties
Authorization: Bearer {2|m6HXiaCEvZNs1PqjLNfq6KkjvAFOpsURT0EgLC1o0cebfdd0}

GET http://localhost:8000/api/specialties
Authorization: Bearer {2|m6HXiaCEvZNs1PqjLNfq6KkjvAFOpsURT0EgLC1o0cebfdd0}

POST http://localhost:8000/login
Content-Type: application/x-www-form-urlencoded

email=faustino.stiedemann@example.com&password=password

GET http://localhost:8000/api/patients
Authorization: Bearer {3|8SAUEUeAbmCi7JIxtfdq67grwqM3w68sW0OHksZ48e8c28b1}

POST http://localhost:8000/login
Content-Type: application/x-www-form-urlencoded

email=justyn94@example.com&password=password

GET http://localhost:8000/api/specialties
Authorization: Bearer {4|NDfmQENSxKFbnd2PnTKl2vS2SKej3a6BQn4FPWE7bbceb5a1}

POST http://localhost:8000/login
Content-Type: application/x-www-form-urlencoded

email=maxime@gmail.com&password=password

GET http://localhost:8000/api/patients
Authorization: Bearer {5|ZSRswKvPEUqlUMajuo5x5W4LeCTE2lmkVVPPk8Q0cfb3e7a9}

GET http://localhost:8000/api/patient/{16}
Authorization: Bearer {5|ZSRswKvPEUqlUMajuo5x5W4LeCTE2lmkVVPPk8Q0cfb3e7a9}